spring.datasource.url=jdbc:postgresql://postgres:5432/order_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
customer-service.url=http://customer-service:8081
restaurant-service.url=http://restaurant-service:8082
eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
eureka.instance.prefer-ip-address=true
app.jwt.secret=${JWT_SECRET}
app.internal.service-secret=${INTERNAL_SERVICE_SECRET}
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# Feign circuit breaker
spring.cloud.openfeign.circuitbreaker.enabled=true

# Actuator
management.endpoints.web.exposure.include=health,info,circuitbreakers,circuitbreakerevents
management.health.circuitbreakers.enabled=true
management.endpoint.health.show-details=always
