spring.datasource.url=jdbc:postgresql://postgres:5432/order_db
customer-service.url=http://customer-service:8081
restaurant-service.url=http://restaurant-service:8082

eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
app.internal.service-secret=InternalSecret123

spring.rabbitmq.host=rabbitmq
